baseURL: https://pabotesu.dev
languageCode: ja-jp
title: /var/log/pabotesu
theme: hugo-pabotesu-theme
copyright: "&copy; 2023 pabotesu"

menu:
  header:
    - name: About
      weight: 1
      url: /about

    - name: Archives
      weight: 2
      url: /archives

    - name: Tags
      weight: 3
      url: /tags
       # newtab: true

params:
  showsource: true
  contenturl: https://github.com/pabotesu/pabotesu.github.io/tree/main/content/
  description: my-post-contents
  favicon: #favicon
  image: #ogp image
  postnav: true

markup:
  highlight:
    guessSyntax: true
    style: monokai #see https://xyproto.github.io/splash/docs/all.html
